services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    wa72_jsonrpc.jsonrpccontroller:
        public: true
        class: 'Wa72\JsonRpcBundle\Controller\JsonRpcController'
        tags: ['controller.service_arguments']